### ISSUE TITLE
A potential blocking bug in internal/cli/studio/pull.go

### ISSUE THREAD

**Issue by xuxiaofan1203** [warpstreamlabs/bento#133]
https://github.com/warpstreamlabs/bento/blob/94feafd4c189e7f16915c369495d99827fee6d6a/internal/cli/studio/pull.go#L87-L88
The endless loop terminates when the cancelFunc done() get executed to select `case <-sigCtx.Done()`: 
https://github.com/warpstreamlabs/bento/blob/94feafd4c189e7f16915c369495d99827fee6d6a/internal/cli/studio/pull.go#L118-L132
However, the  `defer done()` and the loop are in the same goroutine, which leads to the loop doesn't terminates forever and  done() can't get executed. I think we should create a new goroutine to execute the loop. So that the `defer done()` can get executed to avoid blocking bug.

**Comment by richardartoul** [comment]
Is this a real race you ran into, or something you found with static analysis/LLM?

**Comment by xuxiaofan1203** [comment]
> Is this a real race you ran into, or something you found with static analysis/LLM?

Hello, We are doing a work on static detection of golang concurrency vulnerabilities. The bug is reported by our analyzer, and I double checked it, thinking it is a true positive. So I do this developer feedback to you.

**Comment by xuxiaofan1203** [comment]
> Is this a real race you ran into, or something you found with static analysis/LLM?

Excuse me, can you help to confirm the bug?

**Comment by richardartoul** [comment]
This is an unused/unsupported part of this library that will be removed soon, so I'm closing this issue.
