### ISSUE TITLE
A potential goroutine leak in internal/impl/influxdb/metrics_influxdb.go

### ISSUE THREAD

**Issue by xuxiaofan1203** [warpstreamlabs/bento#134]
Hello, I found a potential bug.
The i.ctx, i.cancel are created by context.WithCancel
https://github.com/warpstreamlabs/bento/blob/94feafd4c189e7f16915c369495d99827fee6d6a/internal/impl/influxdb/metrics_influxdb.go#L139
And a new goroutine is created here. https://github.com/warpstreamlabs/bento/blob/94feafd4c189e7f16915c369495d99827fee6d6a/internal/impl/influxdb/metrics_influxdb.go#L190
Only when i.cancel() is called,the function loop can return succesfully
https://github.com/warpstreamlabs/bento/blob/94feafd4c189e7f16915c369495d99827fee6d6a/internal/impl/influxdb/metrics_influxdb.go#L243-L246
However, I can't find any `i.cancel()` in metrics_influxdb.go. Maybe we should call `i.cancel()` in a method to avoid goroutine leak.

**Comment by richardartoul** [comment]
Is this a real race you ran into, or something you found with static analysis/LLM?

**Comment by xuxiaofan1203** [comment]
> Is this a real race you ran into, or something you found with static analysis/LLM?

Hello, we are doing a work on static detection of golang concurrency vulnerabilities. The bug is reported by our analyzer, and I double checked it, thinking it is a true positive. So I do this developer feedback to you.

**Comment by xuxiaofan1203** [comment]
> Is this a real race you ran into, or something you found with static analysis/LLM?

Excuse me, can you help to confirm the bug?

**Comment by richardartoul** [comment]
We don't have time to investigate this for you. Even if its a real bug, the implications are minor (one goroutine leak per process run, not a big deal). If you want to repro a real issue / provide a P.R to fix it, feel free and we'll review more carefully.
