### ISSUE TITLE
docs: Update SECURITY.md to reflect correct versioning

### ISSUE THREAD

**Issue by gregfurman** [warpstreamlabs/bento#28]
See [SECURITY.md](https://github.com/warpstreamlabs/bento/blob/main/SECURITY.md):

Some clear issues:
- Versions need fixing
- Perhaps mention the underlying  MIT Benthos mirror
- Does security@warpstreamlabs.com exist?

**Comment by caleb-warpstream** [comment]
Yep - security@warpstreamlabs.com does exist

**Comment by caleb-warpstream** [comment]
https://github.com/warpstreamlabs/bento/pull/29
