### ISSUE TITLE
Broken Link to bento-plugin-example 

### ISSUE THREAD

**Issue by jem-davies** [warpstreamlabs/bento#32]
Under the[ Plugin Section ](https://github.com/warpstreamlabs/bento#plugins) in the root level README.md there is a link to a non-existent repo [example-repo](https://github.com/warpstreamlabs/bento-plugin-example).

**Comment by gregfurman** [comment]
Yeah looks like it. At the time I made https://github.com/warpstreamlabs/bento/pull/22 to fix this but seems to have moved to https://github.com/redpanda-data/redpanda-connect-plugin-example.

Else, we can always include it in the repo under a subdirectory?

**Comment by jem-davies** [comment]
I think options are: 

-  Remove the sentence in README.md that includes the link and only link the API docs. _interim fix_ -> raise new issue.
-  Fork the connect-plugin-example and update the link.
-  Include the examples in this repo - as you suggest. (just that having them in a separate repo is a part of the example in a way?)

I understand those example plugins are pretty old now, and there is need to update them.

**Comment by gregfurman** [comment]
Those are fair suggestions. I am inclined towards forking the repo and having us maintain it. The example plugin, in my experience, was really helpful. In my opinion, anything to help drive adoption is a plus.

**Comment by jem-davies** [comment]
I agree - going with the fork is the best way I think .

**Comment by jem-davies** [comment]
https://github.com/warpstreamlabs/bento/pull/52

**Comment by jem-davies** [comment]
https://github.com/warpstreamlabs/bento/pull/52
