### ISSUE TITLE
website not redeployed

### ISSUE THREAD

**Issue by jem-davies** [warpstreamlabs/bento#45]
Should the website github action redeploy when there is a succesful push to main?

**Comment by richardartoul** [comment]
That would be convenient! Feel free to submit a P.R

**Comment by jem-davies** [comment]
https://github.com/warpstreamlabs/bento/actions/workflows/pages/pages-build-deployment 

Where is the definition of this cicd pipeline, should it be in [here](https://github.com/warpstreamlabs/bento/tree/main/.github/workflows)?

**Comment by jem-davies** [comment]
@epot looks like you did the work on the fork for the deployment of the new docs site? 

Is there a github action yaml definition for this already written?

**Comment by richardartoul** [comment]
I *think* these commands just need to be run: https://github.com/warpstreamlabs/bento/blob/main/website/README.md

**Comment by epot** [comment]
I'll double check tomorrow from my laptop but I think it was 'yarn build' and then 'yarn deploy'.

**Comment by epot** [comment]
Sorry I forgot to circle back here, I confirm those commands above were the ones I ran the one time I updated the doc.
