### ISSUE TITLE
Repo has no description 

### ISSUE THREAD

**Issue by jem-davies** [warpstreamlabs/bento#48]
![image](https://github.com/warpstreamlabs/bento/assets/131159520/8f03bdd3-1d50-4c10-ba18-a2bd2e84ce86)

**Comment by jem-davies** [comment]
Adding tags and a description might improve visibility of repo.

**Comment by gregfurman** [comment]
Should we use the original tagline "Fancy stream processing made operationally mundane"?

I'm happy to think of some options, definitely an opportunity to get creative 🤔
