### ISSUE TITLE
Like debezium

### ISSUE THREAD

**Issue by AngeloBestetti** [warpstreamlabs/bento#57]
Any plans to have a input connector like debezium to capture transaction logs aka CDC?

Will be nice to have the same capability

**Comment by jem-davies** [comment]
Hi, we are certainly looking to add more connectors to Bento, there are no plans right now for CDC specifically, I would suggest raising an issue for a connector and we can go from there.

**Comment by nickchomey** [comment]
I've opened a discussion with a proposal to solve this in a comprehensive and (hopefully) easy way

https://github.com/warpstreamlabs/bento/discussions/396
