### ISSUE TITLE
http should have 'bento' as default `root_path`

### ISSUE THREAD

**Issue by kmpm** [warpstreamlabs/bento#61]
See https://warpstreamlabs.github.io/bento/docs/components/http/about for a currently bad example

**Comment by gregfurman** [comment]
Hey Peter! Think there are a couple of these inconsistencies peppered around the repo -- so appreciate you raising this.

**Comment by gregfurman** [comment]
Fixed in https://github.com/warpstreamlabs/bento/pull/63
